cmake_minimum_required(VERSION 3.20)
project(UwU_Engine VERSION 0.1.0 LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(CMAKE_C_STANDARD 17)      
set(CMAKE_C_STANDARD_REQUIRED ON)
set(CMAKE_C_EXTENSIONS OFF)  

set(CMAKE_SKIP_INSTALL_RULES TRUE)
set(BUILD_TESTING OFF CACHE BOOL "Disable tests" FORCE)
set(CMAKE_SUPPRESS_REGENERATION TRUE)

set_property(GLOBAL PROPERTY USE_FOLDERS ON)
set_property(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "CMake Utils")

set(PLATFORM "x64")

if(DEFINED CMAKE_VS_PLATFORM_NAME AND NOT "${CMAKE_VS_PLATFORM_NAME}" STREQUAL "")
    set(PLATFORM "${CMAKE_VS_PLATFORM_NAME}")
endif()

message(STATUS "PLATFORM = ${PLATFORM}")
message(STATUS "CMAKE_VS_PLATFORM_NAME = ${CMAKE_VS_PLATFORM_NAME}")
message(STATUS "CMAKE_GENERATOR_PLATFORM = ${CMAKE_GENERATOR_PLATFORM}")

set(OUTPUT_DIR "${CMAKE_SOURCE_DIR}/bin/$<CONFIG>-${PLATFORM}")
set(INT_DIR "${CMAKE_SOURCE_DIR}/bin-int/$<CONFIG>-${PLATFORM}")


add_subdirectory(UwU_Engine)
add_subdirectory(Sandbox)

set_property(DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY VS_STARTUP_PROJECT Sandbox)